spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc-secretsmanager:${DB_URL}
    username: ${DB_USERNAME}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
